version: "3.0"

services:
  api:
    container_name: "annollm"
    build:
      context: .
      args:
        PYTHON_VERSION: 3.11.3
    restart: always
    env_file:
      - .env
    tty: true
    ports:
      - "${PORT}:5000"
    ipc: "host"
